repos:
  - repo: local
    hooks:
      - id: uv-export-docs
        name: Export docs requirements
        language: system
        entry: uv run task docs-lock
        files: ^(uv\.lock|pyproject\.toml)$
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
