; SPDX-FileCopyrightText: 2025 Rayference
;
; SPDX-License-Identifier: GPL-3.0-or-later

[pytest]
python_files = bench_*.py
python_functions = bench_*
python_classes = Bench*
addopts =
    --benchmark-enable
    --benchmark-columns=mean,stddev
    -v
